name: Node CI

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, update
      run: |
        npm ci
        npm run build --if-present
        git config --local user.email "ess_president@me.com"
        git config --local user.name "steelydylan"
        git commit -m "chore(update) periodical update" -a
      env:
        CI: true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
